# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[package]
name = "vertex"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
